# Generated by Django 4.1.3 on 2022-12-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='autumn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='beauty_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='other_titles',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='spring',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='summer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='winter',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
